### ISSUE TITLE
Paginating and find out the total amount of records

### ISSUE THREAD

**Issue by JanStevens** [omohokcoj/filterable#1]
Hello,

When implementing a frontend to filterable that allows to search / order / paginate on Lists and ecto records, I noticed that there is no way to find out the total amount of records when a search + ordering is performed.

This is needed when rendering pagination helpers, you don't want to show a next link when you know there won't be any records to show on the next page.

It would be helpful if this gets returned in the response in `apply_filters`. 

### Example
Note that I'm using a regular list instead of ecto models
```elixir
defmodule Filter do
  use Filterable.DSL

  @options param: :q, cast: &String.downcase/1
  filter name(list, value) do
    list |> Enum.filter(&(String.contains?(String.downcase(&1["name"]), value)))
  end

  # Basic copy past of what paginateable generates + adaption for Lists
  @options param: [:page, :per_page], default: [page: 1, per_page: 10], cast: :integer, share: false
  filter paginate(list, %{page: page, per_page: per_page}) do
    list |> Enum.slice((page - 1) * per_page, per_page)
  end

  @options param: [:sort, :order], default: [order: :desc], cast: :atom, share: false
  filter sort(list, %{sort: field, order: :asc}) do
    list |> Enum.sort_by(&(&1[Atom.to_string(field)]), &<=/2)
  end

  filter sort(list, %{sort: field, order: :desc}) do
    list |> Enum.sort_by(&(&1[Atom.to_string(field)]), &>=/2)
  end
end
```

### Propose
Add a new `@option` flag that indicates that this filter is the pagination filter and should be run at the end. This way you can store the total amount of items currently returned by other filters. Then this value can be returned when `apply_filters` is run.

```elixir
{:ok, result, filter_values, total} = Filter.apply_filters(items, params)
```

**Comment by JanStevens** [comment]
I managed to work around it by returning a tuple instead of a list in the paginate filter

```elixir
@options param: [:page, :per_page], default: [page: 1, per_page: 10], cast: :integer, share: false
  filter paginate(list, %{page: page, per_page: per_page}) do
    paginated = list |> Enum.slice((page - 1) * per_page, per_page)
    {paginated, Enum.count(list)}
  end
```

This does work and I can now extract the total value using

```elixir
{:ok, {result, total} filter_values} = Filter.apply_filters(items, params)
```

Would be cool if filters could also set `filter_values` or some additional meta data during runtime

**Comment by omohokcoj** [comment]
@JanStevens unfortunately we can't treat `pagination` filter some way different than other filters.
also it would be wrong to generate/return some custom metadata inside filter.

your solution with tuple that contains result and counters is good enough.
also you can create some custom helper (let's call it `MetadataHelper`) to generate metadata suitable for your frontend.

btw, thanks for stopping by 😄

**Comment by JanStevens** [comment]
@omohokcoj Sure understand that, what about setting metadata some way inside filters? 

How would the helper help? After the filters are run I don't have access to the total amount of records so it needs to be in the filter.

**Comment by omohokcoj** [comment]
@JanStevens `filterable` is not designed to generate custom metadata, and i don't think it should do that. it just returns a map of filter values. 
so you can use these filter values to generate json response and metadata that fits your frontend.
