### ISSUE TITLE
filtering on boolean: false does not add the clause in the query

### ISSUE THREAD

**Issue by goravbhootra** [omohokcoj/filterable#12]
Hi,

I added the following code for filtering on a boolean column `archived`

```
defmodule MyApp.Registrations.RegistrationFilters do
  use Filterable.DSL
  use Filterable.Ecto.Helpers
  import Ecto.Query, warn: false

  field(:archived)
end
```

when I try the following, it works: 
```
{:ok, query, filters} = RegistrationFilters.apply_filters(query, %{archived: true})
```

with result being:
```
{:ok,
 #Ecto.Query<from r0 in MyApp.Registrations.Registration, as: :registration,
  where: r0.archived == ^true, order_by: [desc: r0.inserted_at]>,
 %{archived: true}}
```

but if I run the same with filtering on `false`, the clause does not get added in query. It does show up in  filters though:
```
{:ok, query, filters} = RegistrationFilters.apply_filters(query, %{archived: false})
```

returns:
```
{:ok,
 #Ecto.Query<from r0 in MyApp.Registrations.Registration, as: :registration,
  order_by: [desc: r0.inserted_at]>, %{archived: false}}
```

Are we supposed to use some different format for the boolean values?

Best regards,
Gorav

**Comment by omohokcoj** [comment]
@goravbhootra thanks for reporting this bug!
it has been fixed in 0.7.1 release - https://hex.pm/packages/filterable/0.7.1
