### ISSUE TITLE
Filterable.FilterError: "only name and surname allowed"

### ISSUE THREAD

**Issue by PhilWaldmann** [omohokcoj/filterable#13]
https://github.com/omohokcoj/filterable/blob/125bb3638f22022113e06aab03b4dab97265950c/lib/filterable/ecto/helpers.ex#L72

Should be changed to something useful ;)

Thanks,
Philipp

**Comment by omohokcoj** [comment]
haha, nice catch, thanks @PhilWaldmann 
is has been fixed in 0.7.2 release
