### ISSUE TITLE
convert /posts?q=castle&author=Kafka&year=1926 to /posts/castle/author/Kafka/year/1926?

### ISSUE THREAD

**Issue by niccolox** [omohokcoj/filterable#5]
can I use filterable to convert the ? = pattern to SEO friendly / ?

**Comment by omohokcoj** [comment]
@niccolox yes it's possible. 
filterable doesn't depend/rely on any framework related features.
all you need is just to fetch necessary params and pass them to filterable.

you can try the following approach (if you're on phoenix):
`get "/posts/:post/author/:author/year/:year", PostsController, :index`

so castle/Kafka/1926 will be treated as respective controller params.
```elixir
conn.params
=> %{'author' => 'Kafka', 'post' => 'castle', 'year' => '1926'}
```
and:
```elixir
  def index(conn, params) do
    with {:ok, query, filter_values} <- apply_filters(Post, conn),
         posts                       <- Repo.all(query),
     do: render(conn, "index.json", posts: posts, meta: filter_values)
  end
```

hope it solves your problem.
