### ISSUE TITLE
Can this be made to work with Phoenix channels?

### ISSUE THREAD

**Issue by bryonwinger** [omohokcoj/filterable#6]
We are currently using Filterable in our app successfully with controllers and separate filter modules.  We're at a point now where this would also be really useful when fetching data through Phoenix channels for async requests.

Is this possible now or are there plans to add it in the future?

**Comment by omohokcoj** [comment]
@bryonwinger, i'm not sure if i correctly understand your problem but if you just need to use filterable inside phoenix channel instead of controller then you can use filter modules:

```elixir
defmodule UserFilters do
  use Filterable
  import Ecto.Query

  filterable share: false do
    @options cast: :integer
    filter age(query, value) when value < 120 do
      query |> where(age: ^value)
    end
  end
end
```

and then in your channel:
```elixir
{:ok, users, _filter_params} = UserFilters.apply_filters(User, %{age: 22})
```

Hope it solves your problem.

**Comment by bryonwinger** [comment]
Thanks for the tip.

It seems our issue is related to accessing the same filter module from both a controller and a channel. The filters are set up like `filter title(query, value, _conn) do` which was breaking when calling from the channel as this only passed 2 arguments.

For now we're getting around this on the channel side by passing the params in a %Plug.Conn{} struct to apply_filters like so: `apply_filters!(SomeSchema, %Plug.Conn{params: params})`.

I haven't had time to mess with it much more, but I'll update if I find a better solution.

**Comment by omohokcoj** [comment]
@bryonwinger thank you for your response, i think i understand your problem now.
So you can create separate filters module using macros from `Filterable.DSL`:
```elixir
defmodule ArticleFilters do
  use Filterable.DSL
  import Ecto.Query

  filter title(query, value) do
    query |> where(title: ^value)
  end
end
```

and then use this filter in your controller:
```elixir
defmodule MyApp.ArticleController do
  use MyAppWeb, :controller
  use Filterable

  filterable ArticleFilters, share: false

  def index(conn, params) do
    {:ok, query, filter_values} = apply_filters(Article, msg)
    articles = Repo.all(query)
  end
end
```

and in the channel:
```elixir
defmodule MyApp.RoomChannel do
  use Phoenix.Channel
  use Filterable

  filterable ArticleFilters, share: false

  def handle_info({:ping, msg}, socket) do
    {:ok, query, filter_values} = apply_filters(Article, msg)
    articles = Repo.all(query)
  end
end
```

If you don't need to pass `conn` or any other shared object into filter function then just set `share: false`.

**Comment by bryonwinger** [comment]
Thank you!
