### ISSUE TITLE
undefined function filterable/1

### ISSUE THREAD

**Issue by AgustinCroce** [omohokcoj/filterable#7]
Hi, I am trying to use filterable in a phoenix project, I have installed version 0.6.0. When i compile the project I got the next Error:

```
== Compilation error in file lib/project/movement/movement_filters.ex ==
** (CompileError) lib/project/movement/movement_filters.ex:5: undefined function filterable/1
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:198: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

The code of movement_filters is a copy of the code in the documentation

```
defmodule PostFilters do
  use Filterable.DSL
  use Filterable.Ecto.Helpers

  filterable do
    filter title(query, value, _conn) do
      query |> where(title: ^value)
    end

    @options cast: :integer
    filter stars(query, value, _conn) do
      query |> where(stars: ^value)
    end
  end
end
```

Thanks.

**Comment by omohokcoj** [comment]
@AgustinCroce oh it's a mistake - `filterable` is not a part of `Filterable.DSL`.
In your case there is no need to use `filterable` macro - you can simply remove it and everything should work.
Where have you found that code snippet? Can't find it in readme.md.
