### ISSUE TITLE
cast: :atom can cause a memory leak

### ISSUE THREAD

**Issue by brodeuralexis** [omohokcoj/filterable#8]
As documented in [Erlang](http://erlang.org/doc/efficiency_guide/advanced.html), an atom is never garbage collected.  One should therefore take extreme precaution when converting a binary to an atom from uncontrolled input.

Using the following filter,
```ex
@options cast: :atom
filter sort_by(query, value, conn), do: #...
```

When called with a random value, each random value will be converted to an atom, regardless of whether or not it is indeed a valid value for this parameter.

A default BEAM configuration will have a limit of 1,048,576 atoms.  Since BEAM applications tend to have long up times, such a limit could be reached quite easily simply from API consumers mistakes.

## Suggested Solution
Since sometimes, not checking for the validity of the value when casting to an atom is sometimes desired, allow it through an option like `cast: :atom_unchecked`.

To allow one to validate the value before it is cast, `cast: {:atom, [:value1, :value2, value3]}` could be used.

To prevent breaking changes to users of this library, we could keep the present `cast: :atom` option, but display a deprecation warning until the next major release.  After displaying the warning, it can simply forward it's arguments to `cast: :atom_unchecked`.

**Comment by omohokcoj** [comment]
@brodeuralexis thank you for reposting this!
closed due to https://github.com/omohokcoj/filterable/pull/10
