### ISSUE TITLE
Possible to use filterable on existing query?

### ISSUE THREAD

**Issue by makeitrein** [omohokcoj/filterable#9]
Hey @omohokcoj - really enjoying my time with filterable, has been much smoother than trying to work with another DSL on top of SQL. 

Is it possible to use filterable on top of a query rather than just a schema? My use case is that I'd like to get all my join tables and computed columns up front and then filter on those, rather than duplicating the joins in the filterable macro.

i.e. right now, the order of operations is
`Fic.apply_filters(conn) |> Fic.get_all_join_tables`
and I'd like to do
`Fic.get_all_join_tables |> Fic.apply_filters(conn)`

My get_all_join_tables query looks like this:
 ```
def get_all_join_tables(query) do
    from f in query,
         left_join: reviews in assoc(f, :reviews),
         group_by: f.id,
         preload: [
           :submitter,
           :author,
           :genres,
           reviews: :submitter,
         ],
         select: %{
          f |
           review_count: fragment("count(?) as review_count", reviews.id),
           review_avg: fragment("coalesce(?::float, 0) as review_avg", avg(reviews.rating))
         }
  end
```

And one of my filterable blocks look like this...
```
@options top_param: :search, cast: :integer
    filter review_avg(query, value, _conn) do
      from f in query,
           left_join: reviews in assoc(f, :reviews),
           having: avg(reviews.rating) > ^value
    end
```

Ideally, I wouldn't have to left_join reviews again and could build off the work I did on the get_all_join_tables.

Any suggestions? Thx again for open sourcing this.

**Comment by makeitrein** [comment]
A reasonable workaround that I've discovered is to place a default filter function at the top of the filterable block so it runs first every time, e.g.

```
filterable do

    @options default: "LEAVE_DEFAULT_SO_THIS_ALWAYS_RUNS"
    filter base_query(query, value, _conn) do
      get_all_join_tables query
    end
```

**Comment by omohokcoj** [comment]
Hey @makeitrein, thanks for using filterable!

Yeah, you can do it using `base_query` filter.
But better solution might be to use `Filterable.apply_filter` function.
I assume `Fic` is an ecto model and it uses `Filterable.Phoenix.Model` macros.
So you should be able to do it like this:

```elixir
Fic.get_all_join_tables |> Filterable.apply_filters(conn.params, Fic.Filterable)
# or even
Fic.get_all_join_tables |> Fic.Filterable.apply_filters(conn.params)
```

All filters defined in ecto model (or phoenix controller) are stored in `.Filterable` submodule which is generated by `filterable do` macro.

But if your model filters don't use any ecto/phoenix features (like conn, default schema) then you can simply use `Filterable` module inside your ecto model.

```elixir
defmodule Fic do
  use Filterable

  filterable do
  ...
  end
end

Fic.get_all_join_tables |> Fic.apply_filters(conn.params)
```

You can pass `conn` to filters using `share` option:
```elixir
Fic.get_all_join_tables |> Fic.apply_filters(conn.params, share: conn)
```

If you don't need to use `conn` in your filters then you can just remove it from filter function arguments:
```elixir
filter base_query(query, value) do
```

Hope you will find a solution that fits you best 😉

**Comment by makeitrein** [comment]
Lovely! 

`Fic.get_all_join_tables |> Fic.apply_filters(conn.params)` seems like it works great without dropping into the Filterable module. (You are correct that Fic is an ecto model).

Going to take another look at filterable's codebase tomorrow to see how this works exactly.

Also good suggestion on removing conn - unnecessary for me at this point. Biggest challenge now is going to be seeing if all this up-front join optimization is going to be worth it...

**Comment by makeitrein** [comment]
@omohokcoj filterable doing work on https://ficdb.com, many thx again
